In [5]:
%load_ext autoreload
%autoreload 2

import numpy as np
from DROLinearRegression import _construct_row_map, _reverse_row_map, leverage_scores, block_lewis_weights, DROLinearRegression

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


In [6]:
d = 3
n_each = 5
m = 10

design_test = list(np.random.rand(m, n_each, d))
response_test = list(np.ones((m, n_each)))
identity_test = np.array([np.eye(1, d, i) for i in range(d)])

In [7]:
design_test

[array([[7.40848005e-01, 7.21451845e-01, 7.84595528e-01],
        [7.00042620e-01, 7.89736435e-01, 4.23298468e-01],
        [2.65255529e-01, 3.20331757e-01, 7.56145879e-04],
        [3.96844823e-01, 2.59689138e-01, 1.34782964e-01],
        [5.93390535e-01, 6.53442272e-01, 5.74216310e-01]]),
 array([[0.06034785, 0.73918496, 0.08643872],
        [0.81631554, 0.17669647, 0.22699755],
        [0.88064195, 0.98641832, 0.02613863],
        [0.18674933, 0.04437002, 0.70673717],
        [0.8810666 , 0.5667119 , 0.31712707]]),
 array([[0.28737005, 0.73953839, 0.6175454 ],
        [0.27685868, 0.9643756 , 0.67286393],
        [0.27147868, 0.85257982, 0.67838916],
        [0.60916385, 0.87749138, 0.02995323],
        [0.54030157, 0.23936731, 0.26648379]]),
 array([[0.3706361 , 0.02605838, 0.19267078],
        [0.42310758, 0.21788135, 0.68837024],
        [0.18956081, 0.80719421, 0.3716837 ],
        [0.70202959, 0.67102372, 0.61730154],
        [0.01601095, 0.05170496, 0.66244396]]),
 array([[0.6

In [8]:
combined = np.concatenate([np.array(design_test), np.array(response_test)[:, :, np.newaxis]], axis=2)

In [9]:
combined

array([[[7.40848005e-01, 7.21451845e-01, 7.84595528e-01, 1.00000000e+00],
        [7.00042620e-01, 7.89736435e-01, 4.23298468e-01, 1.00000000e+00],
        [2.65255529e-01, 3.20331757e-01, 7.56145879e-04, 1.00000000e+00],
        [3.96844823e-01, 2.59689138e-01, 1.34782964e-01, 1.00000000e+00],
        [5.93390535e-01, 6.53442272e-01, 5.74216310e-01, 1.00000000e+00]],

       [[6.03478502e-02, 7.39184961e-01, 8.64387158e-02, 1.00000000e+00],
        [8.16315539e-01, 1.76696466e-01, 2.26997551e-01, 1.00000000e+00],
        [8.80641947e-01, 9.86418322e-01, 2.61386345e-02, 1.00000000e+00],
        [1.86749332e-01, 4.43700165e-02, 7.06737172e-01, 1.00000000e+00],
        [8.81066601e-01, 5.66711903e-01, 3.17127070e-01, 1.00000000e+00]],

       [[2.87370050e-01, 7.39538389e-01, 6.17545397e-01, 1.00000000e+00],
        [2.76858684e-01, 9.64375599e-01, 6.72863929e-01, 1.00000000e+00],
        [2.71478678e-01, 8.52579823e-01, 6.78389161e-01, 1.00000000e+00],
        [6.09163854e-01, 8.7749138

In [10]:
blw = block_lewis_weights(identity_test, p=10)

m = 3, n = 3, d = 3


In [13]:
config = {
    "p": 2,
    "GeometryType": "Lewis",
    "eps": 1e-3,
}

drtest = DROLinearRegression(design_test, response_test, config)

m = 10, n = 50, d = 4


In [15]:
x = getattr(drtest, "x")

In [18]:
x

array([0.68537299, 0.52612974, 0.72856038])

In [20]:
np.linalg.pinv(np.concatenate(np.array(design_test), axis=0)) @ np.concatenate(np.array(response_test))

array([0.68537299, 0.52612974, 0.72856038])